# Global section
global:
  tls:
    # options: suse-private-ai, letsEncrypt, secret
    source: suse-private-ai
    issuerName: suse-private-ai

    # This section to be filled out when using letsEncrypt as the tls source
    letsEncrypt:
      environment: staging
      email: none@example.com
      ingress:
        class: ""

    # Additional Trusted CAs.
    # Enable this flag and add your CA certs as a secret named tls-ca-additional in the suse-private-ai namespace.
    additionalTrustedCAs: false


# Ollama subchart overrides - see the charts/ollama for additional entries
ollama:
  image:
    repository: registry.opensuse.org/home/esampson/ai/15_6_container/suse/private-ai/ollama
    pullPolicy: IfNotPresent
    tag: ""
  ingress:
    enabled: false #Disabled - ollama endpoint is internal. Do not enable ingress.
  defaultModel: "gemma:2b"
  ollama:
    models:
    - "gemma:2b"

# open-webui subchart overrides - see the charts/open-webui for additional entries
open-webui:
  ollama:
    enabled: false #Disabled as we install ollama seperately
  pipelines:
    ingress:
      enabled: false #Disabled - pipeline endpoint is internal
  ollamaUrls:
  - http://suse-private-ai-ollama.suse-private-ai.svc.cluster.local:11434 #Internally accessible ollama endpoint
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "v0.3.32"
    pullPolicy: "IfNotPresent"
  ingress:
    enabled: true
    class: ""
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    host: suse-ollama-webui
    tls: true
    existingSecret: suse-private-ai-tls
  extraEnvVars:
  - name: DEFAULT_MODELS
    value: "gemma:2b"
  - name: DEFAULT_USER_ROLE
    value: "user"
  - name: VECTOR_DB
    value: "milvus"
  - name: MILVUS_URI
    value: http://suse-private-ai-milvus.suse-private-ai.svc.cluster.local:19530

# milvus subchart overrides - see the charts/milvus for additional entries
milvus:
  enabled: true
  cluster:
    enabled: true
  etcd:
    global:
      imagePullSecrets:
        - application-collection
    persistence:
      storageClassName: ""
  minio:
    mode: standalone
    persistence:
      storageClass: ""
  pulsar:
    bookkeeper:
      volumes:
        journal:
          local_storage: false
          storageClassName: ""
        ledgers:
          local_storage: false
          storageClassName: ""
        common:
          local_storage: false
          storageClassName: ""
    zookeeper:
      volumes:
        data:
          storageClassName: ""
    broker:
      volumes:
        data:
          storageClassName: ""
