dependencies:
- name: etcd
  version: 0.2.1
  repository: oci://dp.apps.rancher.io/charts
  condition: etcd.enabled
  tags:
    - etcd
- name: minio
  version: 5.2.0
  repository: oci://dp.apps.rancher.io/charts
  condition: minio.enabled
  tags:
    - minio
- name: pulsar
  version: 3.7.0
  repository: https://pulsar.apache.org/charts
  condition: pulsar.enabled
  tags:
    - pulsar
- name: kafka
  version: 15.5.1
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  condition: kafka.enabled
  tags:
    - kafka
